on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-linux, x86_64-windows, x86_64-macos, aarch64-linux, aarch64-macos ]
    runs-on: ubuntu-latest
    name: Ziege - ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.13.0
      - run: zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.target }}
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: ziege-${{matrix.target}}
          path: zig-out
      
